steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '--build-arg', 'apiName=$TRIGGER_NAME', '--build-arg', 'workerSize=0.1', '--build-arg', 'runtime=4.4.0', '--build-arg', 'workers=1', '--build-arg', 'enviroment=STAGING', '-f', 'DockerFile', '.' ]
